In [12]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv('../data/diabetes_prediction_dataset.csv')

In [14]:
df.shape

(100000, 9)

In [15]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [16]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [18]:
df.duplicated().sum()

np.int64(3854)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.shape

(96146, 9)

In [22]:
df.sample(5)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
28646,Male,32.0,0,0,never,20.90,4.0,126,0
39363,Male,43.0,0,0,not current,27.76,6.1,240,1
75578,Female,62.0,0,0,ever,37.52,8.8,300,1
40024,Male,9.0,0,0,No Info,17.61,5.7,126,0
96662,Female,31.0,0,0,never,35.80,6.6,80,0